version: '3.9'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/frontend/Dockerfile
    container_name: web
    ports:
      - "3000:3000"

  api:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - web
